const placesToVisit = ["Faisal Masjid","Tokyo","Paris","TMaldives","The Taj Mahal" ];
console.log("Original order:", placesToVisit);
console.log("Alphabetical order:", [...placesToVisit].sort());
console.log("Original order:", placesToVisit);
console.log("Reverse alphabetical order:", [...placesToVisit].sort().reverse());
console.log("Original order:", placesToVisit);
console.log("Reversed order:", placesToVisit.reverse());
console.log("Reversed order again:", placesToVisit.reverse());
console.log("Alphabetical order:", placesToVisit.sort());
console.log("Reverse alphabetical order:", placesToVisit.sort().reverse());
